package config

import (
	"bytes"
	"strings"
	"text/template"
)

// Draft is what jw init found in a repository, to be written as a config
// the user then finishes by hand.
type Draft struct {
	Project string
	Match   string // origin URL; set only for a personal config
	Root    string
	Setup   []string
	Env     []DraftEnv
}

// DraftEnv is an ignored env file worth copying into each worktree.
type DraftEnv struct {
	File      string
	Localhost []LocalhostRef // lines pointing at a local port
}

// LocalhostRef is one KEY=value whose value contains localhost:<port>.
type LocalhostRef struct {
	Key   string
	Value string // the value with the port replaced by {port.SERVICE}
	Port  string
}

var draftTmpl = template.Must(template.New("config").Funcs(template.FuncMap{
	"quote": quote,
}).Parse(`# jw config for {{.Project}} — generated by ` + "`jw init`" + `.
# Every key is optional: delete what you don't need, uncomment what you do.
# Reference: https://github.com/brya0x/jw#config
{{if .Match}}
match     = {{quote .Match}}   # this file applies to that repository only
{{- end}}
root      = {{quote .Root}}
workspace = {{quote .Project}}
branch    = "feat/{name}"

# Run in every new worktree, with the JW_* variables exported.
setup = [
{{- range .Setup}}
  {{quote .}},
{{- end}}
]

# Each service gets its own port per worktree: 20000 + slot*100 + offset.
# Name them after what they run and use {port.<name>} anywhere below.
[ports]
# web = 0
# api = 1

# jw dev <service>. One command replaces jw; several get one pane each.
[dev]
# web = ["pnpm dev --port {port.web} --strictPort"]
{{range .Env}}
# Copied from the main checkout into every new worktree.
[[env]]
file = {{quote .File}}
{{- if .Localhost}}
# These point at a local port. Pick the service (add it to [ports]) and
# uncomment, so each worktree talks to its own:
# set = { {{range $i, $r := .Localhost}}{{if $i}}, {{end}}{{$r.Key}} = {{quote $r.Value}}{{end}} }
{{- range .Localhost}}
#   {{.Key}} is localhost:{{.Port}} today
{{- end}}
{{- end}}
{{end}}`))

// Render writes d as a commented TOML config.
func (d Draft) Render() (string, error) {
	var b bytes.Buffer
	if err := draftTmpl.Execute(&b, d); err != nil {
		return "", err
	}
	return b.String(), nil
}

// quote makes a TOML basic string.
func quote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}
