//! Drafting a project config from what a repository shows: setup from its
//! lockfiles, the ignored env files to copy and the local ports they point
//! at. Port of internal/commands/init.go and internal/core/config/template.go;
//! the rendered text is byte for byte what Go writes.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::connectors::git::{Repo, project_name};
use crate::core::config;
use crate::layout::{Node, quote};

/// What init found in a repository, to be written as a config the user then
/// finishes by hand.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Draft {
    pub project: String,
    /// Origin URL; set only for a personal config.
    pub r#match: String,
    pub root: String,
    pub setup: Vec<String>,
    pub env: Vec<DraftEnv>,
}

/// An ignored env file worth copying into each worktree.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct DraftEnv {
    pub file: String,
    /// Lines pointing at a local port.
    pub localhost: Vec<LocalhostRef>,
}

/// One KEY=value whose value contains localhost:<port>.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct LocalhostRef {
    pub key: String,
    /// The value with the port replaced by {port.SERVICE}.
    pub value: String,
    pub port: String,
}

impl Draft {
    /// The draft as a commented TOML config (template.go's draftTmpl).
    pub fn render(&self) -> String {
        let mut s = format!(
            "# jw config for {} — generated by `jw init`.\n\
             # Every key is optional: delete what you don't need, uncomment what you do.\n\
             # Reference: https://github.com/brya0x/jw#config\n",
            self.project
        );
        if !self.r#match.is_empty() {
            s += &format!(
                "\nmatch     = {}   # this file applies to that repository only",
                quote(&self.r#match)
            );
        }
        s += &format!(
            "\nroot      = {}\n\
             workspace = {}   # herdr workspace; \"{{name}}\" gives each stream its own\n\
             branch    = \"feat/{{name}}\"\n\
             \n\
             # Run in every new worktree, with the JW_* variables exported.\n\
             setup = [",
            quote(&self.root),
            quote(&self.project)
        );
        for cmd in &self.setup {
            s += &format!("\n  {},", quote(cmd));
        }
        s += "\n]\n\
              \n\
              # Each service gets its own port per worktree: 20000 + slot*100 + offset.\n\
              # Name them after what they run and use {port.<name>} anywhere below.\n\
              [ports]\n\
              # web = 0\n\
              # api = 1\n\
              \n\
              # jw dev <service>. One command replaces jw; several get one pane each.\n\
              [dev]\n\
              # web = [\"pnpm dev --port {port.web} --strictPort\"]\n";
        for e in &self.env {
            s += &format!(
                "\n# Copied from the main checkout into every new worktree.\n[[env]]\nfile = {}",
                quote(&e.file)
            );
            if !e.localhost.is_empty() {
                let set: Vec<String> = e
                    .localhost
                    .iter()
                    .map(|r| format!("{} = {}", r.key, quote(&r.value)))
                    .collect();
                s += &format!(
                    "\n# These point at a local port. Pick the service (add it to [ports]) and\n\
                     # uncomment, so each worktree talks to its own:\n\
                     # set = {{ {} }}",
                    set.join(", ")
                );
                for r in &e.localhost {
                    s += &format!("\n#   {} is localhost:{} today", r.key, r.port);
                }
            }
            s += "\n";
        }
        s
    }
}

/// What the setup step of a project's first worktree chose (REQ-117).
#[derive(Debug, Clone, PartialEq)]
pub struct ProjectSetup {
    pub setup: Vec<String>,
    pub env: Vec<String>,
    pub agent: String,
    pub layout: Node,
}

/// The `.jw.toml` the setup step writes: its setup, env files, agent and
/// layout, with plain nvim as the editor.
pub fn render_project(project: &str, p: &ProjectSetup) -> String {
    let mut s = format!(
        "# jw config for {project}, written by jw on its first worktree.\n\
         # Reference: https://github.com/brya0x/jw#config\n"
    );
    if !p.setup.is_empty() {
        s += "\n# Run in every new worktree, with the JW_* variables exported.\nsetup = [";
        for cmd in &p.setup {
            s += &format!("\n  {},", quote(cmd));
        }
        s += "\n]\n";
    }
    for f in &p.env {
        s += &format!(
            "\n# Copied from the main checkout into every new worktree.\n[[env]]\nfile = {}\n",
            quote(f)
        );
    }
    s += &format!(
        "\n[agent]\ndefault = {}\n\n[layout]\neditor = \"nvim\"\n{}",
        quote(&p.agent),
        p.layout.table()
    );
    s
}

/// Writes `<repo>/.jw.toml` for the setup step and loads it back, the way
/// every action will; a file that doesn't load is removed. An existing file
/// is never overwritten.
pub fn write_project(repo: &Repo, p: &ProjectSetup) -> Result<PathBuf> {
    let project = project_name(&repo.remote);
    let path = repo.root.join(".jw.toml");
    if path.exists() {
        bail!("{} already exists", path.display());
    }
    std::fs::write(&path, render_project(&project, p))
        .with_context(|| path.display().to_string())?;
    if let Err(e) = config::load(&repo.root, &repo.remote, &project) {
        let _ = std::fs::remove_file(&path);
        bail!("the new config does not load (please report this): {e:#}");
    }
    Ok(path)
}

/// What init wrote.
#[derive(Debug, Clone)]
pub struct Inited {
    pub path: PathBuf,
    pub draft: Draft,
}

/// Drafts a config for `repo` and writes it: `<repo>/.jw.toml` with
/// `in_repo` (to commit), else the personal config. An existing file is
/// kept unless `force`. The file is loaded back the way every other action
/// will; a draft that doesn't load is a jw bug and isn't left behind.
pub fn init(repo: &Repo, in_repo: bool, force: bool) -> Result<Inited> {
    let project = project_name(&repo.remote);
    let path = init_path(repo, &project, in_repo)?;
    if path.exists() && !force {
        bail!(
            "{} already exists (overwrite it to start over)",
            path.display()
        );
    }
    let draft = detect(repo, &project, !in_repo)?;
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(&path, draft.render()).with_context(|| path.display().to_string())?;
    if let Err(e) = config::load(&repo.root, &repo.remote, &project) {
        let _ = std::fs::remove_file(&path);
        bail!("the generated config does not load (please report this): {e:#}");
    }
    Ok(Inited { path, draft })
}

pub fn init_path(repo: &Repo, project: &str, in_repo: bool) -> Result<PathBuf> {
    if in_repo {
        return Ok(repo.root.join(".jw.toml"));
    }
    Ok(config::dir()?.join(format!("{project}.toml")))
}

/// Looks at the repository and drafts what it can.
pub fn detect(repo: &Repo, project: &str, personal: bool) -> Result<Draft> {
    let mut d = Draft {
        project: project.to_string(),
        root: tildify(&format!("{}-wt", repo.root.display())),
        setup: setup_for(&repo.root),
        ..Draft::default()
    };
    if personal {
        d.r#match = repo.remote.clone();
    }
    for f in repo.ignored_files()? {
        if !is_env_file(&f) {
            continue;
        }
        let localhost = localhost_refs(&repo.root.join(&f))?;
        d.env.push(DraftEnv { file: f, localhost });
    }
    Ok(d)
}

/// Lockfiles and the install command that respects each. Order matters: the
/// first match per ecosystem wins.
const LOCKFILES: &[(&str, &str)] = &[
    ("pnpm-lock.yaml", "pnpm install --frozen-lockfile"),
    ("bun.lock", "bun install --frozen-lockfile"),
    ("bun.lockb", "bun install --frozen-lockfile"),
    ("yarn.lock", "yarn install --frozen-lockfile"),
    ("package-lock.json", "npm ci"),
    ("go.mod", "go mod download"),
    ("Gemfile.lock", "bundle install"),
    ("composer.lock", "composer install"),
    ("Cargo.lock", "cargo fetch"),
];

fn setup_for(root: &Path) -> Vec<String> {
    let mut cmds = Vec::new();
    let mut node = false;
    for (file, cmd) in LOCKFILES {
        if !root.join(file).exists() {
            continue;
        }
        let is_node = ["pnpm", "bun", "yarn", "npm"]
            .iter()
            .any(|p| cmd.starts_with(p));
        if is_node && node {
            continue; // one JS package manager is enough
        }
        node |= is_node;
        cmds.push(cmd.to_string());
    }
    cmds
}

/// .env, .env.local, .env.development… but not templates, which are meant
/// to be committed and copied by hand.
fn is_env_file(path: &str) -> bool {
    let base = path.rsplit('/').next().unwrap_or(path);
    if base != ".env" && !base.starts_with(".env.") {
        return false;
    }
    ![".example", ".sample", ".template", ".dist"]
        .iter()
        .any(|t| base.ends_with(t))
}

/// The KEY=value lines whose value points at a local port. A missing file
/// has none.
fn localhost_refs(path: &Path) -> Result<Vec<LocalhostRef>> {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(e).with_context(|| path.display().to_string()),
    };
    Ok(text.lines().filter_map(localhost_ref).collect())
}

const HOSTS: [&str; 2] = ["localhost:", "127.0.0.1:"];

/// `^\s*(?:export\s+)?(KEY)\s*=\s*(.*(?:localhost|127\.0\.0\.1):(\d+).*)$`,
/// by hand: the port is the one of the last host:port in the value, as the
/// greedy `.*` makes it in Go.
fn localhost_ref(line: &str) -> Option<LocalhostRef> {
    let (key, value_at) = crate::core::envfile::assignment(line)?;
    let value = line[value_at..].trim_start();

    let port = HOSTS
        .iter()
        .flat_map(|h| value.match_indices(h).map(move |(i, _)| i + h.len()))
        .filter_map(|at| {
            let digits = value[at..]
                .find(|c: char| !c.is_ascii_digit())
                .unwrap_or(value.len() - at);
            (digits > 0).then(|| (at, &value[at..at + digits]))
        })
        .max_by_key(|(at, _)| *at)?
        .1;

    let trimmed = value.trim_matches(|c| c == '"' || c == '\'');
    Some(LocalhostRef {
        key: key.to_string(),
        value: replace_ports(trimmed),
        port: port.to_string(),
    })
}

/// Every `localhost:<digits>` and `127.0.0.1:<digits>` gets {port.SERVICE}.
fn replace_ports(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    'scan: while i < s.len() {
        for h in HOSTS {
            if s[i..].starts_with(h) {
                let at = i + h.len();
                let digits = s[at..]
                    .find(|c: char| !c.is_ascii_digit())
                    .unwrap_or(s.len() - at);
                if digits > 0 {
                    out.push_str(h);
                    out.push_str("{port.SERVICE}");
                    i = at + digits;
                    continue 'scan;
                }
            }
        }
        let c = s[i..].chars().next().expect("i is on a char boundary");
        out.push(c);
        i += c.len_utf8();
    }
    out
}

/// A path under the home directory as `~/…`, so the config reads well and
/// survives a different username on another machine.
fn tildify(p: &str) -> String {
    let Ok(home) = config::home() else {
        return p.to_string();
    };
    match Path::new(p).strip_prefix(&home) {
        Ok(rel) if rel.as_os_str().is_empty() => "~".into(),
        Ok(rel) => format!("~/{}", rel.display()),
        Err(_) => p.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::connectors::git::tests::{must_git, new_test_repo};
    use crate::layout::Dir;

    /// REQ-117: the setup step's file loads with what was chosen, and is
    /// never written over an existing one.
    #[test]
    fn write_project_writes_a_config_that_loads() {
        let (_tmp, root) = new_test_repo();
        let repo = Repo::open(&root).unwrap();
        let p = ProjectSetup {
            setup: vec!["pnpm install --frozen-lockfile".into()],
            env: vec![".env.local".into()],
            agent: "codex".into(),
            layout: Node::split(
                Dir::Right,
                0.5,
                Node::leaf("editor"),
                Node::leaf("pnpm dev"),
            ),
        };
        let path = write_project(&repo, &p).unwrap();
        assert_eq!(path, repo.root.join(".jw.toml"));
        let c = config::load(&repo.root, &repo.remote, "x").unwrap();
        assert_eq!(c.setup, p.setup);
        assert_eq!(c.env[0].file, ".env.local");
        assert_eq!(c.agent.default, "codex");
        assert_eq!(c.layout.editor, "nvim");
        assert_eq!(c.layout.tree(), p.layout);
        assert!(write_project(&repo, &p).is_err());

        let bare = ProjectSetup {
            setup: vec![],
            env: vec![],
            agent: "claude".into(),
            layout: Node::leaf("shell"),
        };
        let text = render_project("x", &bare);
        assert!(
            !text.contains("setup") && !text.contains("[[env]]"),
            "{text}"
        );
        let c: config::Config = toml::from_str(&text).unwrap();
        assert_eq!(c.layout.tree(), Node::leaf("shell"));
    }

    fn fixture(name: &str) -> String {
        std::fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("testdata")
                .join(name),
        )
        .unwrap()
    }

    /// The same drafts the Go template rendered into testdata/init-*.go.toml
    /// (see testdata/README.md).
    fn full() -> Draft {
        Draft {
            project: "myapp".into(),
            r#match: "git@github.com:acme/myapp.git".into(),
            root: "~/code/myapp-wt".into(),
            setup: vec![
                "pnpm install --frozen-lockfile".into(),
                "go mod download".into(),
            ],
            env: vec![
                DraftEnv {
                    file: "apps/web/.env.local".into(),
                    localhost: vec![
                        LocalhostRef {
                            key: "API_URL".into(),
                            value: "http://localhost:{port.SERVICE}/v1".into(),
                            port: "8787".into(),
                        },
                        LocalhostRef {
                            key: "WS".into(),
                            value: "ws://127.0.0.1:{port.SERVICE}".into(),
                            port: "9000".into(),
                        },
                    ],
                },
                DraftEnv {
                    file: "apps/api/.env".into(),
                    localhost: Vec::new(),
                },
            ],
        }
    }

    #[test]
    fn render_matches_go_byte_for_byte() {
        assert_eq!(full().render(), fixture("init-full.go.toml"));
        let bare = Draft {
            project: "bare".into(),
            root: "../bare-wt".into(),
            ..Draft::default()
        };
        let text = bare.render();
        assert_eq!(text, fixture("init-bare.go.toml"));
        assert!(
            !text.contains("\nmatch "),
            "a repo config has no match line"
        );
    }

    #[test]
    fn rendered_draft_is_a_valid_config() {
        let c: config::Config = toml::from_str(&full().render()).unwrap();
        assert_eq!(c.r#match, "git@github.com:acme/myapp.git");
        assert_eq!((c.setup.len(), c.env.len()), (2, 2));
        assert!(
            c.env[0].set.is_empty(),
            "the suggestion stays commented out"
        );
    }

    #[test]
    fn env_files() {
        for (path, want) in [
            (".env", true),
            (".env.local", true),
            ("apps/web/.env.development", true),
            (".env.example", false),
            ("apps/.env.local.sample", false),
            (".env.dist", false),
            ("env", false),
            (".envrc", false),
        ] {
            assert_eq!(is_env_file(path), want, "{path}");
        }
    }

    #[test]
    fn localhost_lines() {
        let r = localhost_ref(r#"  export API_URL = "http://localhost:8787/v1""#).unwrap();
        assert_eq!(
            r,
            LocalhostRef {
                key: "API_URL".into(),
                value: "http://localhost:{port.SERVICE}/v1".into(),
                port: "8787".into(),
            }
        );
        let r = localhost_ref("PAIR='localhost:3000,127.0.0.1:4000'").unwrap();
        assert_eq!(r.port, "4000", "the last host:port, like Go's greedy match");
        assert_eq!(r.value, "localhost:{port.SERVICE},127.0.0.1:{port.SERVICE}");
        assert_eq!(localhost_ref("URL=https://example.com"), None);
        assert_eq!(localhost_ref("URL=http://localhost:/x"), None);
        assert_eq!(localhost_ref("# A=localhost:1"), None);
        assert_eq!(localhost_ref("1A=localhost:1"), None);
    }

    #[test]
    fn one_js_package_manager() {
        let d = tempfile::tempdir().unwrap();
        for f in ["package-lock.json", "pnpm-lock.yaml", "go.mod"] {
            std::fs::write(d.path().join(f), "").unwrap();
        }
        assert_eq!(
            setup_for(d.path()),
            ["pnpm install --frozen-lockfile", "go mod download"]
        );
    }

    #[test]
    fn tildify_home_paths() {
        let home = config::home().unwrap();
        assert_eq!(
            tildify(&format!("{}/code/x-wt", home.display())),
            "~/code/x-wt"
        );
        assert_eq!(tildify("/elsewhere/x"), "/elsewhere/x");
    }

    #[test]
    fn detect_then_init_in_repo() {
        let (_d, work) = new_test_repo();
        let repo = Repo::open(&work).unwrap();
        std::fs::write(work.join(".gitignore"), ".env.local\nnode_modules/\n").unwrap();
        std::fs::write(
            work.join(".env.local"),
            "API_URL=\"http://localhost:8787/v1\"\nPLAIN=1\n",
        )
        .unwrap();
        std::fs::create_dir_all(work.join("node_modules/x")).unwrap();
        std::fs::write(work.join("node_modules/x/.env"), "").unwrap();
        std::fs::write(work.join("pnpm-lock.yaml"), "").unwrap();
        must_git(&work, &["status", "--short"]);

        let d = detect(&repo, "myapp", true).unwrap();
        assert_eq!(d.r#match, repo.remote);
        assert_eq!(d.setup, ["pnpm install --frozen-lockfile"]);
        assert_eq!(d.env.len(), 1, "{:?}", d.env);
        assert_eq!(d.env[0].file, ".env.local");
        assert_eq!(d.env[0].localhost[0].port, "8787");

        let got = init(&repo, true, false).unwrap();
        assert_eq!(got.path, repo.root.join(".jw.toml"));
        assert!(got.draft.r#match.is_empty(), "a repo config has no match");
        let c = config::load(&repo.root, &repo.remote, "myapp").unwrap();
        assert_eq!(c.setup, ["pnpm install --frozen-lockfile"]);

        let err = init(&repo, true, false).unwrap_err();
        assert!(err.to_string().contains("already exists"), "{err}");
        init(&repo, true, true).unwrap();
    }
}
